name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - run: git config --global user.name Arcyvilk
      - run: git config --global user.email arcyvilk@gmail.com

      - name: Install dependencies
        run: yarn --cwd docs install --frozen-lockfile

      - name: Build website
        run: yarn docs:deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GH_TOKEN}@github.com/arcybot.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}